[environments.development]
store = "wi0e05-g1"
theme = "175728787793"
ignore = [
  "templates/*.json",
  "templates/**/*.json",
  "sections/*.json",
  "config/settings_data.json",
  "locales/*",
]

[environments.production]
store = "wi0e05-g1"
theme = "175728787793"
ignore = [
  "templates/*.json",
  "templates/**/*.json",
  "sections/*.json",
  "config/settings_data.json",
  "locales/*",
]
allow-live = true
