[environments.development]
store = "your-store"
theme = "123456789012"
ignore = [
  "templates/*.json",
  "templates/**/*.json",
  "sections/*.json",
  "config/settings_data.json",
  "locales/*",
]

[environments.production]
store = "your-store"
theme = "987654321098"
ignore = [
  "templates/*.json",
  "templates/**/*.json",
  "sections/*.json",
  "config/settings_data.json",
  "locales/*",
]
allow-live = true
