[environments.development]
store = "ss-dev-1"
theme = "135066452052"
allow-live = true
ignore = [
  "templates/*.json",
  "templates/**/*.json",
  "sections/*.json",
  "config/settings_data.json",
  "locales/*",
]

[environments.production]
store = "ss-dev-1"
theme = "129419968596"
allow-live = true
ignore = [
  "templates/*.json",
  "templates/**/*.json",
  "sections/*.json",
  "config/settings_data.json",
  "locales/*",
]
