[environments.development]
store = "ss-dev-1"
theme = "128597491796"
ignore = ["templates/*", "config/settings_data.json", "locales/*"]

[environments.production]
store = "ss-dev-1"
theme = "128597491796"
ignore = ["templates/*", "config/settings_data.json", "locales/*"]
allow-live = true
